#pragma once

#define PRINT_ANGLE_AND_REALOAD_TIME

#define MAX_FIT_TRIES 500

#define SCREEN_WIDTH 900
#define SCREEN_HEIGHT 600
#define GAMEPLAY_AREA_WIDTH SCREEN_WIDTH
#define GAMEPLAY_AREA_HEIGHT (SCREEN_HEIGHT - 30)

#define RELOAD_TIME_IN_SECONDS 1
#define BULLET_SPEED 10.0
#define NUMBER_OF_TARGETS 27
#define GAME_LENGHT 20


#ifdef PRINT_ANGLE_AND_REALOAD_TIME
	#define _DEBUG
#endif