#pragma once

#define PRINT_ANGLE_AND_REALOAD_TIME

#define MAX_FIT_TRIES 500

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define GAMEPLAY_AREA_WIDTH SCREEN_WIDTH
#define GAMEPLAY_AREA_HEIGHT (SCREEN_HEIGHT - 30)

#define RELOAD_TIME_IN_SECONDS 0.3
#define BULLET_SPEED 10.0


#ifdef PRINT_ANGLE_AND_REALOAD_TIME
	#define _DEBUG
#endif