#pragma once

#define PRINT_ANGLE_AND_REALOAD_TIME

#define _DEBUG

#define MAX_FIT_TRIES 500

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define GAMEPLAY_AREA_WIDTH SCREEN_WIDTH
#define GAMEPLAY_AREA_HEIGHT (SCREEN_HEIGHT - 30)

#define CZAS_PRZELADOWANIA_W_SEKUNDACH 0.1
#define PREDKOSC_POCISKU 10.0